version: "3.0"
services:
  weatherapi:
    build: .
    container_name: weatherApi
    ports:
      - 80:8000
    env_file:
      - ./src/weatherApi/.env
    volumes:
      - ./src/weatherApi:/weatherApi
    depends_on:
      - db
      - redis

  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=weatherApi_user
      - POSTGRES_PASSWORD=weatherApi_pass
      - POSTGRES_DB=weatherApi
    ports:
      - 5432:5432

  redis:
    restart: unless-stopped
    image: redis:7.2.4

volumes:
  postgres_data: